version: '3.8'

services:
  # ==========================================
  # ИНФРАСТРУКТУРА (Базы данных и очереди)
  # ==========================================
  postgres:
    image: postgres:15-alpine
    container_name: piano_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: piano_transcription
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - piano_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d piano_transcription"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: piano_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - piano_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: piano_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - piano_network

  # ==========================================
  # МИКРОСЕРВИСЫ ПЛАТФОРМЫ
  # ==========================================
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile # Убедись, что добавишь Dockerfile в папку backend
    container_name: piano_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=piano_transcription
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - CLIENT_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - piano_network

  worker:
    build: 
      context: ./worker
    container_name: piano_ml_worker
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      - piano_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile # Убедись, что добавишь Dockerfile в папку frontend
    container_name: piano_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:8000/transcription
    depends_on:
      - backend
    networks:
      - piano_network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  piano_network:
    driver: bridge